version: '3'

services:

  elasticsearch:
    init: true
    image: elasticsearch:7.17.0
    container_name: elasticsearch
    volumes:
      - type: bind
        source: ./elasticsearch/data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic-stack
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    init: true
    image: kibana:7.17.0
    container_name: kibana
    volumes:
      - type: bind
        source: ./kibana/data
        target: /usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - elastic-stack
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  timings:
    init: true
    image: godaddy/timings:latest
    container_name: timings
    volumes:
      - "${CONFIGFILE}:/src/config/default.js"
      - ./timings/logs:/src/logs
    ports:
      - "80:80"
    networks:
      - elastic-stack
    environment:
      NODE_ENV: "production"
      ES_HOST: "elasticsearch"
      KB_HOST: "${HOSTNAME}"
      API_HOST: "${HOSTNAME}"
      DEBUG: "true"
      IS_DOCKER: "true"
    depends_on:
      - elasticsearch
      - kibana
    command: ['node', './server.js']

networks:
  elastic-stack:
