version: '3'

services:

  elasticsearch_v8:
    image: elasticsearch:8.0.0
    container_name: elasticsearch_v8
    volumes:
      - type: bind
        source: ./logs/elasticsearch_v8
        target: /var/log/elasticsearch_v8
      - type: bind
        source: ./esdata_v8
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.authc.token.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=false
      - path.logs=/var/log/elasticsearch_v8
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

  kibana_v8:
    image: kibana:8.0.0
    container_name: kibana_v8
    volumes:
      - type: bind
        source: ./logs/kibana_v8
        target: /var/log/kibana_v8
      - type: bind
        source: ./kibanadata_v8
        target: /usr/share/kibana/data
    ports:
      - "5601:5601"
    environment:
      - SERVERNAME=kibana
      - elasticsearch.hosts=[http://elasticsearch_v8:9200]
    depends_on:
      - elasticsearch_v8
