version: '3'

services:

  elasticsearch_v7:
    init: true
    image: elasticsearch:7.17.0
    container_name: elasticsearch_v7
    volumes:
      - type: bind
        source: ./data_v7
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic-stack
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana_v7:
    init: true
    image: kibana:7.17.0
    container_name: kibana_v7
    volumes:
      - type: bind
        source: ./data_v7
        target: /usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - elastic-stack
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch_v7:9200
    depends_on:
      - elasticsearch_v7

networks:
  elastic-stack: