version: '3'

services:

  elasticsearch_v5:
    init: true
    image: elasticsearch:5.6.16
    container_name: elasticsearch_v5
    volumes:
      - type: bind
        source: ./data_v5
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic-stack
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana_v5:
    init: true
    image: kibana:5.6.16
    container_name: kibana_v5
    volumes:
      - type: bind
        source: ./data_v5
        target: /usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - elastic-stack
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_URL=http://elasticsearch_v5:9200
    depends_on:
      - elasticsearch_v5

networks:
  elastic-stack: